"use client";

import { useState } from "react";

interface HandoffItem {
  id: string;
  label: string;
  description: string;
  path: "both" | "complex-only";
}

const handoffItems: HandoffItem[] = [
  {
    id: "h-pr",
    label: "GitHub PR link",
    description: "Feature branch in the sandbox repo. Branch name: feature/<ticket-id>-<description>. This is the reference the dev will use — not a merge-ready PR into production.",
    path: "both",
  },
  {
    id: "h-vercel",
    label: "Vercel preview URL (approved version)",
    description: "The exact URL that was approved by the Carlos. Do NOT redeploy after approval — the URL must stay frozen as the reference. Screenshot it as a backup.",
    path: "both",
  },
  {
    id: "h-figma",
    label: "Figma frame link (annotated)",
    description: "Link to the approved Figma frame — locked so no further edits. Frame should have annotations for interactions (e.g. 'opens modal on click', 'hover state'). Not required for Simple path features.",
    path: "complex-only",
  },
  {
    id: "h-components",
    label: "Component inventory",
    description: "List every component that is new or modified. For each: component name, file path in sandbox, props with types, and whether it's net-new or a modification of an existing component.",
    path: "both",
  },
  {
    id: "h-tokens",
    label: "New design tokens (if any)",
    description: "Any new colors, spacing values, font sizes, or border radii introduced. Format as: token name → value → where it's used. If none were added, write 'No new tokens — uses existing system'.",
    path: "complex-only",
  },
  {
    id: "h-copy",
    label: "All copy and strings finalized",
    description: "Every string, label, placeholder, error message, and empty state copy is final and approved. No 'Lorem ipsum' or 'TBD'. Dev should never have to guess at copy.",
    path: "both",
  },
  {
    id: "h-states",
    label: "Edge states documented",
    description: "Loading state, empty state, and error state are all built and visible in the Vercel preview. Each state should be documented: how it triggers, what it shows.",
    path: "both",
  },
  {
    id: "h-qa",
    label: "Claude QA checklist",
    description: "Generated by Claude using Playwright: a diff of the Vercel preview vs production at the same routes. Dev must confirm each item before the feature is marked done.",
    path: "both",
  },
  {
    id: "h-notes",
    label: "Implementation notes for dev",
    description: "Any context the dev needs that isn't obvious from the code: API endpoints to wire up, feature flags to add, third-party integrations, things Claude couldn't implement in the sandbox.",
    path: "both",
  },
];

export function HandoffPackage() {
  const [pathFilter, setPathFilter] = useState<"both" | "complex-only">("both");
  const [checked, setChecked] = useState<Set<string>>(new Set());

  const toggle = (id: string) =>
    setChecked((prev) => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n; });

  const visibleItems =
    pathFilter === "both"
      ? handoffItems
      : handoffItems.filter((i) => i.path !== "complex-only");

  const done = visibleItems.filter((i) => checked.has(i.id)).length;
  const total = visibleItems.length;
  const allDone = done === total;

  return (
    <section id="handoff" className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold text-zinc-100">Handoff Package</h2>
        <p className="text-zinc-400 text-sm mt-1">
          Everything the dev needs to implement into production. No assumptions, no back-and-forth.
        </p>
      </div>

      {/* Path filter */}
      <div className="flex items-center gap-3 flex-wrap">
        <span className="text-xs text-zinc-500 uppercase tracking-wider">Feature type:</span>
        <div className="flex gap-1 rounded-lg border border-zinc-700 p-1">
          {[
            { value: "both" as const, label: "Complex (Option A)" },
            { value: "complex-only" as const, label: "Simple (Option B)" },
          ].map((opt) => (
            <button
              key={opt.value}
              onClick={() => setPathFilter(opt.value)}
              className={`px-3 py-1.5 rounded text-xs font-medium transition-all duration-150
                ${pathFilter === opt.value ? "bg-zinc-100 text-zinc-900" : "text-zinc-400 hover:text-zinc-200"}`}
            >
              {opt.label}
            </button>
          ))}
        </div>
        {pathFilter === "complex-only" && (
          <span className="text-xs text-zinc-500">Figma artifacts not required for Simple path</span>
        )}
      </div>

      {/* Progress */}
      <div className="flex items-center gap-3">
        <div className="flex-1 h-1.5 rounded-full bg-zinc-700 overflow-hidden">
          <div
            className={`h-full rounded-full transition-all duration-500 ${allDone ? "bg-emerald-500" : "bg-blue-500"}`}
            style={{ width: `${total > 0 ? (done / total) * 100 : 0}%` }}
          />
        </div>
        <span className="text-xs text-zinc-400 w-20 text-right">{done}/{total} items ready</span>
      </div>

      {/* Items */}
      <div className="space-y-2">
        {visibleItems.map((item) => {
          const isDone = checked.has(item.id);
          return (
            <div
              key={item.id}
              className={`rounded-xl border p-4 transition-all duration-200
                ${isDone ? "border-emerald-500/30 bg-emerald-500/5 opacity-70" : "border-zinc-700/60 bg-zinc-800/40"}`}
            >
              <div className="flex items-start gap-3">
                <button
                  onClick={() => toggle(item.id)}
                  className={`flex-shrink-0 mt-0.5 w-5 h-5 rounded border-2 flex items-center justify-center transition-all
                    ${isDone ? "bg-emerald-500 border-emerald-500" : "border-zinc-600 hover:border-zinc-400"}`}
                >
                  {isDone && (
                    <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                  )}
                </button>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className={`text-sm font-medium ${isDone ? "line-through text-zinc-500" : "text-zinc-100"}`}>
                      {item.label}
                    </span>
                    {item.path === "complex-only" && (
                      <span className="text-xs px-2 py-0.5 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-400">
                        Complex only
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-zinc-500 mt-1 leading-relaxed">{item.description}</p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Done state */}
      {allDone && total > 0 && (
        <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/5 p-5 text-center">
          <svg className="w-8 h-8 text-emerald-400 mx-auto mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <p className="text-emerald-300 font-semibold">Handoff package complete</p>
          <p className="text-zinc-400 text-sm mt-1">Send this checklist to the dev along with the PR link and Vercel URL.</p>
        </div>
      )}
    </section>
  );
}
